FROM docker.io/library/archlinux:latest@sha256:5906892165fc79b4e282e36f24802528bcee2bd2896982ad771045341e15db5c

RUN pacman -Syu --noconfirm \
    && pacman -S --noconfirm \
    gcc \
    just \
    python

WORKDIR /tmp/pyquante2
COPY ./ ./
