FROM docker.io/library/archlinux:latest@sha256:204e91950fd364961088a01773eee9012243b7e965fed42b1d82d12416190782

RUN pacman -Syu --noconfirm \
    && pacman -S --noconfirm \
    gcc \
    just \
    python

WORKDIR /tmp/pyquante2
COPY ./ ./
